language: r

cache: packages
sudo: required

warnings_are_errors: true

r_packages:
  - rgeos
  - sp
  - covr
  
r_binary_packages:
  -rgdal

notifications:
  email:
    on_success: change
    on_failure: change

after_success:
  - Rscript -e 'covr::codecov()'