language: r
cache: packages
warnings_are_errors: true

sudo: required

before_install:
  Rscript -e 'update.packages(ask = FALSE)'

r_packages:
  - covr
  
r_binary_packages:
  - rgdal
  - rgeos
  - sp

notifications:
  email:
    on_success: change
    on_failure: change