language: r
cache: packages
sudo: required

warnings_are_errors: true

env:
  global:
    - _R_CHECK_FORCE_SUGGESTS_=FALSE
    
befone_install:
  Rscript -e 'update.packages(ask = FALSE)'

r_packages:
  - rgeos
  - sp
  
r_binary_packages:
  - rgdal

notifications:
  email:
    on_success: change
    on_failure: change
