language: r
cache: packages
sudo: required

warnings_are_errors: true

env:
  global:
    - _R_CHECK_FORCE_SUGGESTS_=FALSE

apt_packages:
  - libgdal-dev

r_packages:
  - rgdal
  - rgeos
  - sp

notifications:
  email:
    on_success: change
    on_failure: change
