language: c

before_install:
  - curl -OL http://raw.github.com/craigcitro/r-travis/master/scripts/travis-tool.sh
  - chmod 755 ./travis-tool.sh
  - ./travis-tool.sh bootstrap
  - sudo apt-get install -qq libgeos-dev

install:
  - ./travis-tool.sh r_install rgeos
  - ./travis-tool.sh r_binary_install sp
  - ./travis-tool.sh install_deps
  
env:
  global:
    - _R_CHECK_FORCE_SUGGESTS_=FALSE

script:
  - ./travis-tool.sh run_tests

after_failure:
  - ./travis-tool.sh dump_logs

notifications:
  email:
    on_success: change
    on_failure: change
