language: r
cache: packages
warnings_are_errors: true

sudo: required

before_install:
  - sudo add-apt-repository ppa:ubuntugis/ubuntugis-unstable --yes
  - sudo apt-get --yes --force-yes update -qq
  - sudo apt-get install --yes libudunits2-dev libproj-dev libgeos-dev libgdal-dev libhdf5-serial-dev libhdf5-dev libhdf5-7

r_packages:
  - rgdal
  - rgeos
  - sp

notifications:
  email:
    on_success: change
    on_failure: change