language: r
cache: packages
sudo: required

warnings_are_errors: true

env:
  global:
    - _R_CHECK_FORCE_SUGGESTS_=FALSE

before_install:
  - sudo apt-get install --yes libgeos-dev libgdal-dev libproj-dev

r_packages:
  - rgdal
  - rgeos
  - sp

notifications:
  email:
    on_success: change
    on_failure: change
