language: r

cache: packages

sudo: required

befone_install:
  - Rscript -e 'update.packages(ask = FALSE)'
  - sudo apt-get install --yes libproj-dev libgeos-dev libgdal-dev

warnings_are_errors: true

r_packages:
  - rgdal
  - rgeos
  - sp

notifications:
  email:
    on_success: change
    on_failure: change
